//
// Created by Tip on 2020/5/19.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tip_net_dns_DNSUtil */

#ifndef _Included_com_tip_net_dns_DNSUtil
#define _Included_com_tip_net_dns_DNSUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tip_net_dns_DNSUtil
 * Method:    getHostByName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tip_net_dns_DNSUtil_getHostByName
        (JNIEnv *env, jclass jno, jstring jstr);

#endif
}